services:
  dev-al-fest-2025:
    build: ..
    container_name: dev-al-fest-2025
    restart: on-failure:5

    ports:
      - 127.0.0.1:3026:80

    networks:
      - main

networks:
  main:
    external: true
