services:
  art-lab-fest-web-dev:
    build:
      context: ../..
      dockerfile: deploy/Dockerfile
    container_name: art-lab-fest-web-dev
    restart: on-failure:5

    ports:
      - 127.0.0.1:3026:80

    networks:
      - main

networks:
  main:
    external: true
