worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /usr/local/openresty/nginx/conf/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    upstream backend {
        server art-lab-backend:8000 fail_timeout=0;
    }

    upstream dev_backend {
        server al-dev-backend:8000 fail_timeout=0;
    }

    server {
        listen 80;
        server_name fest.art-labyrinth.org;

        location /api/v1/ {
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }

        location = /2025 {
            return 301 /2025/;
        }

        location /2025/ {
            root /usr/share/nginx/html;
            index index.html;
            autoindex off;
            try_files $uri /2025/index.html;
        }

        location = /2026 {
            return 301 /2026/;
        }

        location /2026/ {
            root /usr/share/nginx/html;
            index index.html;
            autoindex off;
            try_files $uri /2026/index.html;
        }

        # Base site (main)
        location / {
            root /usr/share/nginx/html/main;
            index index.html;
            autoindex off;
            try_files $uri $uri/ /index.html;
        }

        error_page 500 502 503 504 /index.html;
    }

    server {
        listen 80;
        server_name dev.art-labyrinth.org;

        location /api/v1/ {
            proxy_pass http://dev_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }

        location = /2025 {
            return 301 /2025/;
        }

        location /2025/ {
            root /usr/share/nginx/html;
            index index.html;
            autoindex off;
            try_files $uri /2025/index.html;
        }

        location = /2026 {
            return 301 /2026/;
        }

        location /2026/ {
            root /usr/share/nginx/html;
            index index.html;
            autoindex off;
            try_files $uri /2026/index.html;
        }

        # Base site (main)
        location / {
            root /usr/share/nginx/html/main;
            index index.html;
            autoindex off;
            try_files $uri $uri/ /index.html;
        }

        error_page 500 502 503 504 /index.html;
    }
}
