name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    # runs-on: [self-hosted, art-lab-run]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy Services
        run: |
          docker compose up -d --build

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    # runs-on: [self-hosted]
    runs-on: [self-hosted, fest2025]
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy Dev
        run: |
          docker compose -f ./dev/docker-compose.yml up -d --build
