name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, art-lab-run]
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy Services
        run: |
          docker compose build
          docker compose up -d
